app/blog/models.py
# 创建数据库分类
from RealProject import db
from datetime import datetime
from sqlalchemy.dialects.mysql import LONGTEXT
from enum import IntEnum


class BaseModel(db.Model):
    # 基类模型
    __abstract__ = True

    create_time = db.Column(db.DateTime, default=datetime.now) # 创建时间
    update_time = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now) # 更新时间

class Category(BaseModel):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    # 一对多关系
    # posts = db.relationship('Post', back_populates='category')
    posts = db.relationship('Post', backref='category', lazy='dynamic')
    icon = db.Column(db.String(50))

    
    def __repr__(self):
        return '<Category {}>'.format(self.name)
    
class PostPublishType(IntEnum):
    draft = 0 # 草稿
    show = 1 # 展示
    
tags = db.Table('tags',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
    db.Column('post_id', db.Integer, db.ForeignKey('post.id'), primary_key=True)
)


class Post(BaseModel):
    # 文章模型
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    desc = db.Column(db.String(200))
    content = db.Column(LONGTEXT, nullable=False)
    has_type = db.Column(db.Enum(PostPublishType), default=PostPublishType.show, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    #多对多关系
    tags = db.relationship('Tag', secondary=tags, lazy='subquery', backref=db.backref('post', lazy=True))
    
    def __repr__(self):
        return '<Post {}>'.format(self.title)



class Tag(BaseModel):
    """ 文章标签
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)

    def __repr__(self):
        return f'<Tag {self.name}>'

app/admin/views.py
from flask import Flask, render_template, request, redirect, url_for, flash, jsonify, blueprints
from ..auth.views.auth import login_required
from ..blog.models import Category, Tag, Post
from .forms import CategoryForm, PostForm, TagForm
from RealProject import db

bp = blueprints.Blueprint('admin', __name__, url_prefix='/admin', static_folder='static', template_folder='templates')

@bp.route('/')
@login_required
def index():
    return render_template('admin/index.html')

# CRUD for category, tag, post

@bp.route('/category')
@login_required
def category():
    page = request.args.get('page', 1, type=int)
    pagination = Category.query.order_by(-Category.create_time).paginate(page=page, per_page=5, error_out=False)
    category_list = pagination.items
    print(pagination)
    print(category_list)
    return render_template('admin/category.html',
                           category_list = category_list,
                           pagination = pagination)

@bp.route('/category/add', methods=['GET', 'POST'])
@login_required
def category_add():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data, icon=form.icon.data)
        db.session.add(category)
        db.session.commit()
        flash('分类添加成功')
        return redirect(url_for('admin.category'))

    return render_template('admin/category_form.html', form=form, id = 0)

@bp.route('/category/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def category_edit(id):
    category = Category.query.get_or_404(id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        category.icon = form.icon.data
        db.session.commit()
        flash('分类编辑成功')
        return redirect(url_for('admin.category'))

    form.name.data = category.name
    form.icon.data = category.icon
    return render_template('admin/category_form.html', form=form, id=id)

# 删除分类
@bp.route('/category/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def category_delete(id):
    category = Category.query.get_or_404(id)
    if category.posts.count() > 0:
        flash('该分类下有文章，不能删除')
        return redirect(url_for('admin.category'))
    else:
        db.session.delete(category)
        db.session.commit()
        flash('{}类删除成功'.format(category.name))
        return redirect(url_for('admin.category'))


# 文章管理 : 增删改查

@bp.route('/article')
@login_required
def article():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(-Post.create_time).paginate(page=page, per_page=5, error_out=False)
    article_list = pagination.items
    return render_template('admin/article.html',
                           post_list = article_list,
                           pagination = pagination)


@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
def article_add():
    form = PostForm()
    form.category_id.choices = [ (v.id, v.name) for v in Category.query.all() ]
    form.tags.choices = [ (v.id, v.name) for v in Tag.query.all() ]
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    desc=form.desc.data,
                    has_type=form.has_type.data,
                    category_id=int(form.category_id.data),
                    content=form.content.data
        )
        post.tags =  [ Tag.query.get(tag_id) for tag_id in form.tags.data ]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章添加成功')
        return redirect(url_for('admin.article'))
    
    return render_template('admin/article_form.html', form=form, id = 0)

@bp.route('/article/edit/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_edit(post_id):
    # 修改文章
    post = Post.query.get(post_id)
    tags = [tag.id for tag in post.tags]
    form = PostForm(
        title=post.title, desc=post.desc, 
        category_id=post.category.id, has_type=post.has_type.value,
        content=post.content, tags=tags
    )

    form.category_id.choices = [(v.id,v.name) for v in Category.query.all()]
    form.tags.choices = [(v.id,v.name) for v in Tag.query.all()]

    if form.validate_on_submit():
        post.title = form.title.data
        post.desc = form.desc.data
        post.has_type = form.has_type.data
        post.category_id=int(form.category_id.data)
        post.content = form.content.data
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]
        db.session.add(post)
        db.session.commit()
        flash(f'{form.title.data}文章修改成功')
        return redirect(url_for('admin.article'))
    return render_template('admin/article_form.html', form=form)


@bp.route('/article/delete/<int:post_id>', methods=['GET', 'POST'])
@login_required
def article_del(post_id):
    # 删除文章
    post = Post.query.get(post_id)
    if post:  
        db.session.delete(post)
        db.session.commit()
        flash(f'{post.title}文章删除成功')
        return redirect(url_for('admin.article'))
    

@bp.route('/tag')
@login_required
def tag():
    # 查看标签列表
    page = request.args.get('page', 1, type=int)
    pagination = Tag.query.order_by(-Tag.create_time).paginate(page=page, per_page=10, error_out=False)
    tag_list = pagination.items
    return render_template('admin/tag.html', tag_list=tag_list, pagination=pagination)


@bp.route('/tag/add', methods=['GET', 'POST'])
@login_required
def tag_add():
    # 增加标签
    form = TagForm()
    if form.validate_on_submit():
        tag = Tag(name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}添加成功')
        return redirect(url_for('admin.tag'))
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/edit/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_edit(tag_id):
    # 修改标签
    tag = Tag.query.get(tag_id)
    form = TagForm(name=tag.name)
    if form.validate_on_submit():
        tag.name = form.name.data
        db.session.add(tag)
        db.session.commit()
        flash(f'{form.name.data}添加成功')
        return redirect(url_for('admin.tag'))
    return render_template('admin/tag_form.html', form=form)


@bp.route('/tag/del/<int:tag_id>', methods=['GET', 'POST'])
@login_required
def tag_del(tag_id):
    # 删除标签
    tag = Tag.query.get(tag_id)
    if tag:
        db.session.delete(tag)
        db.session.commit()
        flash(f'{tag.name}删除成功')
        return redirect(url_for('admin.tag'))

app/blog/__init__.py
from .views import bp

app/blog/views.py
from flask import Flask, Blueprint, render_template, request, flash, redirect, url_for, g, session


# 创建蓝图

bp = Blueprint('blog', __name__, url_prefix='/blog', static_folder='static', template_folder='templates')

# @bp.route('/')
def index():
    posts = [1,2,3,4,5]
    return render_template('index.html',posts=posts)

app/blog/templates/base.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/bulma.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='css/buefy.min.css') }}">
    {% block extra_head_style %}{% endblock extra_head_style %}   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/buefy@0.9.2/dist/buefy.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css">
    <link rel="stylesheet" href="styles.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
</head>

<body>
    <div id="app" style="height:100%;">
        <div class="container is-fluid1" style="height:100%; ">
            <div class="is-block" style="height:100%;">
                <!-- 导航 -->
                {% block navbar %}     
                <template>
                    <b-navbar spaced shadow>
                        <template #brand>
                            <b-navbar-item>
                                <img src="{{ url_for('blog.static', filename='img/logo.png') }}" alt="FlaskBlog">
                            </b-navbar-item>
                        </template>
                        <template #start>
                            <b-navbar-item href="#">
                                Home
                            </b-navbar-item>
                            <b-navbar-item href="#">
                                Documentation
                            </b-navbar-item>
                            <b-navbar-dropdown label="Info">
                                <b-navbar-item href="#">
                                    About
                                </b-navbar-item>
                                <b-navbar-item href="#">
                                    Contact
                                </b-navbar-item>
                            </b-navbar-dropdown>
                        </template>

                        <template #end>

                        <b-navbar-item tag="div">
                            <!-- 判断用户是否已登录 -->
                            {% if g.user %}              
                            <div class=" buttons">
                                <!-- 获取用户信心 -->
                                <a class="button is-primary">欢迎您 {{ g.user['username'] }}</a>
                                <a class="button is-success" href="{{ url_for('admin.index') }}">个人中心</a>
                                <!-- 显示推出按钮 -->
                                <a class="button is-danger" href="{{ url_for('auth.logout') }}">退出</a>
                            </div>
                            {% else %}
                            <!-- 用户未登录，显示登录注册按钮 -->
                            <div class="buttons">
                                <a class="button is-primary" href="{{ url_for('auth.register') }}">
                                    <strong>Sign up</strong>
                                </a>
                                <a class="button is-light" href="{{ url_for('auth.login') }}">Log in</a>
                            </div>
                            {% endif %}
                        </b-navbar-item>
                        </template>
                    </b-navbar>
                </template>
                {% endblock navbar %}
                <!-- 导航 end -->

                {% block hero %}
                <section class="hero is-medium is-primary">
                    <div class="hero-body">
                        <p class="title">
                            Large hero
                        </p>
                        <p class="subtitle">
                            Large subtitle
                        </p>
                    </div>
                </section>
                {% endblock hero %}

                {% block main %} 
                <div class="box is-marginless is-shadowless is-radiusless">

                    {% block box %}
                    <div class="columns is-multiline">
                        {% for post in posts %}
                        <div class="column is-4-fullhd">
                            <div class="card">
                                <div class="card-image">
                                    <figure class="image is-4by3">
                                        <img src="https://bulma.io/images/placeholders/1280x960.png"
                                            alt="Placeholder image">
                                    </figure>
                                </div>
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="title is-4"><a href="">Flask博客实战 - 掌握增删改查</a> </p>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <p class=" has-text-grey is-size-7"> 
                                            既然我们选择了使用ORM框架，那就必须熟练掌握其提供的增删改查方法，在正式编写视图事前，
                                            本节内容我们先在shell环境中来了解和熟悉其增删改查的基础方法！
                                        </p>
                                        <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                        {% endblock box %}
                    </div>

                    <nav class="pagination" role="navigation" aria-label="pagination">
                        <a class="pagination-previous is-disabled" title="This is the first page">Previous</a>
                        <a class="pagination-next">Next page</a>
                        <ul class="pagination-list">
                          <li>
                            <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">1</a>
                          </li>
                          <li>
                            <a class="pagination-link" aria-label="Goto page 2">2</a>
                          </li>
                          <li>
                            <a class="pagination-link" aria-label="Goto page 3">3</a>
                          </li>
                        </ul>
                    </nav>
                </div>
                {% endblock main %}



                {% block footer %}      
                <div class="footer has-background-black-ter is-marginless">
                    <div class="has-text-centered has-text-grey-light">
                        © 2022 <a class="has-text-grey-light" href="http://www.lotdoc.cn/blog/topic/detail/6/">FlaskBlog博客实战</a> 版权所有 备案号：陕ICP备20005686号
                    </div>
                </div>
                {% endblock footer %}
            </div>

        </div>
    </div>

    <script src="{{ url_for('blog.static', filename='js/vue.js') }}"></script>
    <script src="{{ url_for('blog.static', filename='js/buefy.min.js') }}"></script>
    {% block extra_foot_script %}{% endblock extra_foot_script %}
    <script>
        var app = new Vue({
            el: '#app',
            data: {},
            methods: {}
        })
    </script>
    {% block vue_script %}{% endblock vue_script %}
</body>

</html>

app/blog/templates/index.html
{% extends 'base.html' %}